# Generated by Django 5.2.17 on 2026-08-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_matiere_section_option_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneescolaire',
            name='active',
            field=models.BooleanField(default=False, help_text='Une seule année active pour toute la plateforme.', verbose_name='Année active (nationale)'),
        ),
    ]
