# Generated by Django 5.2.16 on 2026-08-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecoles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('postnom', models.CharField(blank=True, max_length=100, verbose_name='Postnom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=150, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('classe', models.CharField(max_length=50, verbose_name='Classe')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('nom_tuteur', models.CharField(blank=True, max_length=150, verbose_name='Nom du tuteur')),
                ('telephone_tuteur', models.CharField(blank=True, max_length=20, verbose_name='Téléphone tuteur')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='ecoles.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['nom', 'postnom', 'prenom'],
            },
        ),
    ]
