# Generated by Django 5.2.16 on 2026-08-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='numero_identification',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro Identification'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='numero_permanent',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro Permanent'),
        ),
    ]
