# Generated by Django 5.2.16 on 2026-08-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='eleves/photos/', verbose_name='Photo'),
        ),
    ]
