# Generated by Django 5.2.16 on 2026-08-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_classe_scolaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='email_mere',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail mère'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='email_pere',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail père'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='email_tuteur',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail tuteur'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='lien_tuteur',
            field=models.CharField(blank=True, choices=[('pere', 'Père'), ('mere', 'Mère'), ('tuteur', 'Tuteur légal'), ('oncle_tante', 'Oncle / Tante'), ('grand_parent', 'Grand-parent'), ('autre', 'Autre')], max_length=20, verbose_name='Lien de parenté (tuteur)'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom de la mère'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom du père'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='photo_mere',
            field=models.ImageField(blank=True, null=True, upload_to='eleves/parents/', verbose_name='Photo de la mère'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='photo_pere',
            field=models.ImageField(blank=True, null=True, upload_to='eleves/parents/', verbose_name='Photo du père'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='photo_tuteur',
            field=models.ImageField(blank=True, null=True, upload_to='eleves/parents/', verbose_name='Photo du tuteur'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='postnom_mere',
            field=models.CharField(blank=True, max_length=100, verbose_name='Postnom de la mère'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='postnom_pere',
            field=models.CharField(blank=True, max_length=100, verbose_name='Postnom du père'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='prenom_mere',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prénom de la mère'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='prenom_pere',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prénom du père'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='profession_mere',
            field=models.CharField(blank=True, max_length=120, verbose_name='Profession mère'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='profession_pere',
            field=models.CharField(blank=True, max_length=120, verbose_name='Profession père'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='telephone_mere',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone mère'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='telephone_pere',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone père'),
        ),
    ]
