# Generated by Django 5.2.17 on 2026-08-16 19:07

import eleves.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0006_eleve_numero_impot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='code_unique',
            field=models.CharField(default=eleves.models._default_code_unique_eleve, editable=False, help_text='Identifiant stable encodé dans le QR code de l’élève.', max_length=40, unique=True, verbose_name='Code unique QR'),
        ),
    ]
