# Generated by Django 5.2.16 on 2026-08-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StructureOrganisationnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Structure organisationnelle',
                'verbose_name_plural': 'Structures organisationnelles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Antenne',
            fields=[
                ('structureorganisationnelle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecoles.structureorganisationnelle')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Antenne',
                'verbose_name_plural': 'Antennes',
                'ordering': ['province_educationnelle__nom', 'nom'],
            },
            bases=('ecoles.structureorganisationnelle',),
        ),
        migrations.CreateModel(
            name='ProvinceAdministrative',
            fields=[
                ('structureorganisationnelle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecoles.structureorganisationnelle')),
            ],
            options={
                'verbose_name': 'Province administrative',
                'verbose_name_plural': 'Provinces administratives',
                'ordering': ['nom'],
            },
            bases=('ecoles.structureorganisationnelle',),
        ),
        migrations.CreateModel(
            name='ProvinceEducationnelle',
            fields=[
                ('structureorganisationnelle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecoles.structureorganisationnelle')),
                ('province_administrative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces_educationnelles', to='ecoles.provinceadministrative', verbose_name='Province administrative')),
            ],
            options={
                'verbose_name': 'Province éducationnelle',
                'verbose_name_plural': 'Provinces éducationnelles',
                'ordering': ['province_administrative__nom', 'nom'],
            },
            bases=('ecoles.structureorganisationnelle',),
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'école")),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code école')),
                ('type_ecole', models.CharField(choices=[('publique', 'Publique'), ('privee', 'Privée'), ('conventionnee', 'Conventionnée')], default='publique', max_length=20, verbose_name="Type d'école")),
                ('niveau', models.CharField(choices=[('maternelle', 'Maternelle'), ('primaire', 'Primaire'), ('secondaire', 'Secondaire'), ('mixte', 'Mixte')], default='primaire', max_length=20, verbose_name='Niveau')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('directeur', models.CharField(blank=True, max_length=150, verbose_name='Directeur')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('antenne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecoles', to='ecoles.antenne', verbose_name='Antenne')),
                ('province_educationnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecoles', to='ecoles.provinceeducationnelle', verbose_name='Province éducationnelle')),
            ],
            options={
                'verbose_name': 'École',
                'verbose_name_plural': 'Écoles',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='antenne',
            name='province_educationnelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antennes', to='ecoles.provinceeducationnelle', verbose_name='Province éducationnelle'),
        ),
    ]
