# Generated by Django 5.2.16 on 2026-08-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='numero_agrement',
            field=models.CharField(blank=True, max_length=50, verbose_name="N° d'agrément"),
        ),
    ]
