# Generated by Django 5.2.16 on 2026-08-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0002_ecole_numero_agrement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='effectif_mat',
            field=models.PositiveIntegerField(default=0, verbose_name='Effectif MAT'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='effectif_prim',
            field=models.PositiveIntegerField(default=0, verbose_name='Effectif PRIM'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='effectif_sec',
            field=models.PositiveIntegerField(default=0, verbose_name='Effectif SEC'),
        ),
    ]
