# Generated by Django 5.2.16 on 2026-08-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0003_ecole_effectifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='effectifs',
            field=models.PositiveIntegerField(default=0, verbose_name='Effectifs'),
        ),
    ]
