# Generated by Django 5.2.16 on 2026-08-04 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0004_ecole_effectifs_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=40, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('postnom', models.CharField(blank=True, max_length=100, verbose_name='Postnom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('fonction', models.CharField(choices=[('directeur', 'Directeur / Directrice'), ('directeur_etudes', 'Directeur des études'), ('enseignant', 'Enseignant(e)'), ('secretaire', 'Secrétaire'), ('comptable', 'Comptable'), ('surveillant', 'Surveillant(e)'), ('prefet', 'Préfet / Préfète'), ('autre', 'Autre')], default='enseignant', max_length=30, verbose_name='Fonction')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('date_prise_service', models.DateField(blank=True, null=True, verbose_name='Date de prise de service')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnels', to='ecoles.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': "Personnel de l'école",
                'verbose_name_plural': 'Personnels des écoles',
                'ordering': ['nom', 'postnom', 'prenom'],
            },
        ),
    ]
