# Generated by Django 5.2.16 on 2026-08-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0005_personnel_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude GPS'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude GPS'),
        ),
        migrations.CreateModel(
            name='PhotoEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ecoles/photos/', verbose_name='Photo')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('est_principale', models.BooleanField(default=False, verbose_name='Photo principale')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ecoles.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': "Photo d'école",
                'verbose_name_plural': "Photos d'écoles",
                'ordering': ['-est_principale', '-date_ajout'],
            },
        ),
    ]
