# Generated by Django 5.2.16 on 2026-08-05 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0006_ecole_gps_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom de la classe')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ecoles.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['nom'],
                'constraints': [models.UniqueConstraint(fields=('ecole', 'nom'), name='uniq_classe_nom_par_ecole')],
            },
        ),
    ]
