# Generated by Django 5.2.16 on 2026-08-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0008_section_option_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom de la classe'),
        ),
    ]
