# Generated by Django 5.0.4 on 2026-08-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0009_classe_nom_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('agrement', "Arrêté / décision d'agrément"), ('autorisation', "Autorisation d'ouverture"), ('statuts', "Statuts de l'établissement"), ('plan', 'Plan de localisation'), ('attestation_epsp', 'Attestation EPSP'), ('autre', 'Autre document')], default='agrement', max_length=30, verbose_name='Type de document')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Titre / référence')),
                ('fichier', models.FileField(upload_to='ecoles/documents/', verbose_name='Fichier')),
                ('date_document', models.DateField(blank=True, null=True, verbose_name='Date du document')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ecoles.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': "Document d'école",
                'verbose_name_plural': "Documents d'écoles",
                'ordering': ['type_document', '-date_ajout'],
            },
        ),
    ]
