# Generated by Django 5.0.4 on 2026-08-11 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0010_document_ecole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Référence unique (ex. AGR/EPSP/2024/001)', max_length=80, unique=True, verbose_name="N° d'arrêté")),
                ('objet', models.CharField(max_length=255, verbose_name='Objet')),
                ('type_arrete', models.CharField(choices=[('agrement', "Agrément / création d'école"), ('autorisation', "Autorisation d'ouverture"), ('modification', 'Modification de statut'), ('convention', 'Convention'), ('autre', 'Autre')], default='agrement', max_length=30, verbose_name="Type d'arrêté")),
                ('date_arrete', models.DateField(verbose_name="Date de l'arrêté")),
                ('autorite', models.CharField(blank=True, default='EPSP', max_length=150, verbose_name='Autorité émettrice')),
                ('description', models.TextField(blank=True, verbose_name='Description / observations')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='referentiel/arretes/', verbose_name='Fichier (PDF)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Arrêté',
                'verbose_name_plural': 'Arrêtés',
                'ordering': ['-date_arrete', 'numero'],
            },
        ),
        migrations.AlterField(
            model_name='ecole',
            name='numero_agrement',
            field=models.CharField(blank=True, max_length=80, verbose_name="N° d'agrément"),
        ),
        migrations.AddField(
            model_name='documentecole',
            name='arrete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_ecoles', to='ecoles.arrete', verbose_name='Arrêté (référentiel)'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='arrete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecoles', to='ecoles.arrete', verbose_name="Arrêté d'agrément"),
        ),
    ]
