# Generated by Django 5.0.4 on 2026-08-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0011_arrete_referentiel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrete',
            options={'ordering': ['-date_arrete', 'numero'], 'verbose_name': 'Document référentiel', 'verbose_name_plural': 'Documents référentiels'},
        ),
        migrations.AlterField(
            model_name='arrete',
            name='date_arrete',
            field=models.DateField(verbose_name='Date du document'),
        ),
        migrations.AlterField(
            model_name='arrete',
            name='numero',
            field=models.CharField(help_text='Référence unique (ex. AGR/EPSP/2024/001)', max_length=80, unique=True, verbose_name='N° référence'),
        ),
        migrations.AlterField(
            model_name='arrete',
            name='type_arrete',
            field=models.CharField(choices=[('arrete', 'Arrêté'), ('agrement', "Décision d'agrément"), ('autorisation', "Autorisation d'ouverture"), ('modification', 'Modification de statut'), ('convention', 'Convention'), ('autre', 'Autre')], default='arrete', max_length=30, verbose_name='Type de document'),
        ),
    ]
