# Generated by Django 5.0.4 on 2026-08-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0012_document_type_arrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrete',
            name='signataire',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom du signataire'),
        ),
    ]
