# Generated by Django 5.0.4 on 2026-08-13 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0013_arrete_signataire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelecole',
            name='utilisateur',
            field=models.OneToOneField(blank=True, help_text='Compte Educ_RDC lié (ex. enseignant titulaire).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiche_personnel', to=settings.AUTH_USER_MODEL, verbose_name='Compte plateforme'),
        ),
    ]
