# Generated by Django 5.0.4 on 2026-08-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0016_personnel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='niveau',
            field=models.CharField(choices=[('creche', 'Crèche'), ('maternelle', 'Maternelle'), ('primaire', 'Primaire'), ('secondaire', 'Secondaire'), ('mixte', 'Mixte')], default='primaire', max_length=20, verbose_name='Niveau'),
        ),
    ]
