# Generated by Django 5.2.17 on 2026-08-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_autorisationaccesexterieur'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='autorisationaccesexterieur',
            new_name='administrat_statut_ee33d2_idx',
            old_name='administrat_statut_6c0d0d_idx',
        ),
    ]
