# Generated by Django 5.2.16 on 2026-08-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (CDF)')),
                ('type_paiement', models.CharField(choices=[('carte', 'Frais de carte'), ('enrolement', "Frais d'enrôlement"), ('autre', 'Autre')], default='carte', max_length=20, verbose_name='Type de paiement')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('annule', 'Annulé')], default='valide', max_length=20, verbose_name='Statut')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
