# Generated by Django 5.2.17 on 2026-08-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('carte', 'Frais de carte'), ('autre', 'Autre')], default='carte', max_length=20, verbose_name='Type de paiement'),
        ),
    ]
