# Generated by Django 5.2.16 on 2026-08-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(default='2025-2026', max_length=20, verbose_name='Année scolaire')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_enrolement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enrôlement")),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
            ],
            options={
                'verbose_name': 'Enrôlement',
                'verbose_name_plural': 'Enrôlements',
                'ordering': ['-date_enrolement'],
            },
        ),
    ]
