# Generated by Django 5.2.16 on 2026-08-05 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0006_ecole_gps_photos'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='ecoles.ecole', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('agent_national', 'Agent National'), ('agent_provincial', 'Agent Provincial'), ('agent_antenne', 'Agent Antenne'), ('admin_ecole', 'Administratif école'), ('enseignant', 'Enseignant')], default='agent_antenne', max_length=30, verbose_name='Rôle'),
        ),
    ]
