# Generated by Django 5.2.16 on 2026-08-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_utilisateur_ecole_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='classe',
            field=models.CharField(blank=True, help_text="Classe dont l'enseignant est titulaire — limite l'accès aux élèves de cette classe.", max_length=50, verbose_name='Classe (titulaire)'),
        ),
    ]
