# Generated by Django 5.0.4 on 2026-08-16 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_role_agent_province_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialBiometrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(max_length=512, unique=True, verbose_name='ID credential (base64url)')),
                ('public_key', models.BinaryField(verbose_name='Clé publique')),
                ('sign_count', models.PositiveIntegerField(default=0, verbose_name='Compteur de signatures')),
                ('transports', models.JSONField(blank=True, default=list, verbose_name='Transports')),
                ('nom_appareil', models.CharField(blank=True, default='Appareil biométrique', max_length=120, verbose_name='Nom de l’appareil')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date d’enregistrement')),
                ('date_dernier_usage', models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials_biometriques', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Identifiant biométrique',
                'verbose_name_plural': 'Identifiants biométriques',
                'ordering': ['-date_creation'],
            },
        ),
    ]
