# Generated by Django 5.2.16 on 2026-08-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('type_rapport', models.CharField(choices=[('eleves', 'Rapport élèves'), ('ecoles', 'Rapport écoles'), ('cartes', 'Rapport cartes'), ('enrolements', 'Rapport enrôlements'), ('global', 'Rapport global')], default='global', max_length=20, verbose_name='Type')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rapports/', verbose_name='Fichier')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('parametres', models.JSONField(blank=True, default=dict, verbose_name='Paramètres')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-date_generation'],
            },
        ),
    ]
