# Generated by Django 5.2.17 on 2026-08-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='type_rapport',
            field=models.CharField(choices=[('eleves', 'Rapport élèves'), ('ecoles', 'Rapport écoles'), ('cartes', 'Rapport cartes'), ('global', 'Rapport global')], default='global', max_length=20, verbose_name='Type'),
        ),
    ]
