# Generated by Django 5.2.16 on 2026-08-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biometrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='biometrie/photos/', verbose_name='Photo')),
                ('empreinte_hash', models.CharField(blank=True, max_length=128, verbose_name='Hash empreinte (simulé)')),
                ('date_capture', models.DateTimeField(auto_now_add=True, verbose_name='Date de capture')),
                ('validee', models.BooleanField(default=False, verbose_name='Validée')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometrie', to='eleves.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Biométrie',
                'verbose_name_plural': 'Biométries',
            },
        ),
    ]
