# Generated by Django 5.2.16 on 2026-08-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carte', models.CharField(max_length=40, unique=True, verbose_name='Numéro de carte')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_expiration', models.DateField(verbose_name="Date d'expiration")),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='cartes/qr/', verbose_name='QR Code')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('expiree', 'Expirée'), ('annulee', 'Annulée')], default='active', max_length=20, verbose_name='Statut')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes', to='eleves.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Carte scolaire',
                'verbose_name_plural': 'Cartes scolaires',
                'ordering': ['-date_emission'],
            },
        ),
    ]
