# Generated by Django 5.2.16 on 2026-08-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartes', '0001_initial'),
        ('enrolement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='enrolement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carte', to='enrolement.enrolement', verbose_name='Enrôlement'),
        ),
    ]
