# Generated by Django 5.2.16 on 2026-08-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carte',
            name='enrolement',
        ),
    ]
